# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.ehr.com:
  peer0.hospitals.ehr.com:
  peer1.hospitals.ehr.com:
  peer0.patients.ehr.com:
  peer1.patients.ehr.com:

networks:
  byfn: 
services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospitals.ehr.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hospitals.ehr.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hospitals.ehr.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerHospitals
    networks:
      - byfn

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.patients.ehr.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.patients.ehr.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/patients.ehr.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerPatients
    networks:
      - byfn

  orderer.ehr.com:
    extends:
      file:   ../base/docker-compose-base.yaml
      service: orderer.ehr.com
    container_name: orderer.ehr.com
    networks:
      - byfn

  peer0.hospitals.ehr.com:
    container_name: peer0.hospitals.ehr.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer0.hospitals.ehr.com
    networks:
      - byfn

  peer1.hospitals.ehr.com:
    container_name: peer1.hospitals.ehr.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer1.hospitals.ehr.com
    networks:
      - byfn

  peer0.patients.ehr.com:
    container_name: peer0.patients.ehr.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer0.patients.ehr.com
    networks:
      - byfn

  peer1.patients.ehr.com:
    container_name: peer1.patients.ehr.com
    extends:
      file:  ../base/docker-compose-base.yaml
      service: peer1.patients.ehr.com
    networks:
      - byfn
