# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.ehr.com:
    container_name: orderer.ehr.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer.ehr.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer.ehr.com/tls/:/var/hyperledger/orderer/tls
        - orderer.ehr.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
  
  orderer2.ehr.com:
    container_name: orderer2.ehr.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer2.ehr.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer2.ehr.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.ehr.com:/var/hyperledger/production/orderer
    ports:
      - 8050:8050

  orderer3.ehr.com:
    container_name: orderer3.ehr.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer3.ehr.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer3.ehr.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.ehr.com:/var/hyperledger/production/orderer
    ports:
      - 9050:9050


  orderer4.ehr.com:
    container_name: orderer4.ehr.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer4.ehr.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer4.ehr.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.ehr.com:/var/hyperledger/production/orderer
    ports:
      - 10050:10050
  
  
  orderer5.ehr.com:
    container_name: orderer5.ehr.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer5.ehr.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/ehr.com/orderers/orderer5.ehr.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.ehr.com:/var/hyperledger/production/orderer
    ports:
      - 11050:11050

  peer0.hospitals.ehr.com:
    container_name: peer0.hospitals.ehr.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hospitals.ehr.com
      - CORE_PEER_ADDRESS=peer0.hospitals.ehr.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hospitals.ehr.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospitals.ehr.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospitals.ehr.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospitals.ehr.com/peers/peer0.hospitals.ehr.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospitals.ehr.com/peers/peer0.hospitals.ehr.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hospitals.ehr.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.hospitals.ehr.com:
    container_name: peer1.hospitals.ehr.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.hospitals.ehr.com
      - CORE_PEER_ADDRESS=peer1.hospitals.ehr.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.hospitals.ehr.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hospitals.ehr.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospitals.ehr.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospitals.ehr.com/peers/peer1.hospitals.ehr.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospitals.ehr.com/peers/peer1.hospitals.ehr.com/tls:/etc/hyperledger/fabric/tls
        - peer1.hospitals.ehr.com:/var/hyperledger/production

    ports:
      - 8051:8051

      ## Org2 : Patients ----------------

  peer0.patients.ehr.com:
    container_name: peer0.patients.ehr.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.patients.ehr.com
      - CORE_PEER_ADDRESS=peer0.patients.ehr.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.patients.ehr.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.patients.ehr.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.patients.ehr.com:10051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/patients.ehr.com/peers/peer0.patients.ehr.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/patients.ehr.com/peers/peer0.patients.ehr.com/tls:/etc/hyperledger/fabric/tls
        - peer0.patients.ehr.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.patients.ehr.com:
    container_name: peer1.patients.ehr.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.patients.ehr.com
      - CORE_PEER_ADDRESS=peer1.patients.ehr.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.patients.ehr.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.patients.ehr.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.patients.ehr.com:9051
      - CORE_PEER_LOCALMSPID=Org2MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/patients.ehr.com/peers/peer1.patients.ehr.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/patients.ehr.com/peers/peer1.patients.ehr.com/tls:/etc/hyperledger/fabric/tls
        - peer1.patients.ehr.com:/var/hyperledger/production
    ports:
      - 10051:10051
